#!/usr/bin/env python3
"""
Agent Scout — Halo Taxonomy
==============================
Canonical lists of disciplines, areas of expertise, and countries
from the Halo platform. Used by the fit scorer to classify leads.
"""

DISCIPLINES = [
    "Agriculture",
    "Animal Science",
    "Biology",
    "Biomedical Engineering",
    "Chemical Engineering",
    "Chemistry",
    "Civil Engineering",
    "Computer Science",
    "Data Science",
    "Electrical Engineering",
    "Environmental Science",
    "Food Science & Nutrition",
    "Geography",
    "Industrial Engineering",
    "Materials Science",
    "Mathematics",
    "Mechanical Engineering",
    "Physics",
    "Process Engineering",
]

AREAS_OF_EXPERTISE = [
    "Abiotic Stress",
    "Acoustics",
    "Adhesives",
    "Aerodynamics",
    "Aerospace",
    "Aging",
    "Agricultural Engineering",
    "Agricultural Science",
    "Agronomy",
    "Allergies",
    "Analytical Chemistry",
    "Anatomy",
    "Animal Production",
    "Antimicrobials",
    "Artificial Intelligence",
    "Bilayers",
    "Biochemical Engineering",
    "Biochemistry",
    "Biocides",
    "Bioenergy",
    "Biofilms",
    "Bioinformatics",
    "Biological Complexity",
    "Biological Fluid Dynamics",
    "Biological Optics",
    "Bioluminescence",
    "Biomechanics",
    "Biomimetics",
    "Biomolecular Processes",
    "Bionics",
    "Biopharmaceutics",
    "Biophysics",
    "Biosensors",
    "Biosystems",
    "Biotechnology",
    "Botany",
    "Carbohydrate Biochemistry",
    "Cardiovascular",
    "Cell Assembly",
    "Cell Biology",
    "Cell Membrane Transport",
    "Cell Therapy",
    "Chaos",
    "Chemical Physics",
    "Chirality",
    "Chronobiology",
    "Classical Mechanics",
    "Clinical Pharmacology",
    "Coatings",
    "Cognitive Neuroscience",
    "Collective Behavior",
    "Comparative Physiology",
    "Complex Systems",
    "Computational Biology",
    "Computational Chemistry",
    "Conformation & Topology",
    "Crop Cultivation and Harvesting",
    "Cryobiology",
    "Developmental Biology",
    "Diagnostics",
    "Drug Delivery",
    "Earth Science",
    "Ecological Population Dynamics",
    "Ecology",
    "Electric Field Effects",
    "Electrical",
    "Electrochemistry",
    "Electrophysiology",
    "Embryology",
    "Endocrinology",
    "Energy Sources",
    "Energy Storage",
    "Energy Utilization",
    "Entomology",
    "Environmental Chemistry",
    "Epidemiology",
    "Ethnopharmacology",
    "Evolution",
    "Exobiology",
    "Flavor Technology",
    "Fluorescent Biomolecules",
    "Food Chemistry & Biochemistry",
    "Food Engineering & Processing",
    "Food Microbiology",
    "Food Safety",
    "Food Science",
    "Forestry",
    "Gene Therapy",
    "General Chemistry",
    "Genetics",
    "Genomics",
    "Geochemistry & Geophysics",
    "Geology",
    "Geroscience",
    "Graphene",
    "Growth Processes",
    "Hematology",
    "Histocytochemistry",
    "Histology",
    "Hydrobiology",
    "Immunohistochemistry",
    "Immunology",
    "Immunotherapy",
    "Industrial Chemistry",
    "Infectious Diseases",
    "Inorganic Chemistry",
    "Interactions & Forces",
    "Internet of Things",
    "Intracellular Signalling",
    "Intracellular Trafficking",
    "Intracellular Transport",
    "Kinetic Theory",
    "Lipidomics",
    "Machine Learning",
    "Magnetohydrodynamics",
    "Marine Biology",
    "Mathematical Modeling",
    "Mathematical Physics",
    "Medical Physics",
    "Medicinal Chemistry",
    "Membranes",
    "Memory",
    "Metabolomics",
    "Metrology",
    "Microbiology",
    "Microbiome",
    "Microfluidics",
    "Molecular Biology",
    "Molecular Medicine",
    "Morphology",
    "Mycology",
    "Nanoengineering",
    "Nanofluidics",
    "Nanomaterials",
    "Nanotechnology",
    "Natural Resource Management",
    "Nephrology",
    "Network Formation & Growth",
    "Network Optimization",
    "Network Structure",
    "Neuroanatomy",
    "Neurobiology",
    "Neurochemistry",
    "Neurodegeneration",
    "Neuroendocrinology",
    "Neuronal networks",
    "Neuropathology",
    "Neuropharmacology",
    "Neurophysiology",
    "Neuroscience",
    "Nuclear Astrophysics",
    "Nuclear Engineering",
    "Nuclear Reactions",
    "Nutrition",
    "Oceanography",
    "Oncology",
    "Ophthalmology",
    "Optical & Microwave Phenomena",
    "Optics & Lasers",
    "Organic Chemistry",
    "Ornithology",
    "Osteology",
    "Packaging",
    "Parasitology",
    "Particle Astrophysics",
    "Pharmaceutical Chemistry",
    "Pharmacoepidemiology",
    "Pharmacogenetics",
    "Pharmacology",
    "Photobiology",
    "Photonics",
    "Physical Chemistry",
    "Physiology",
    "Plant Biology",
    "Plant Pathology",
    "Plant Physiology",
    "Plasma Interactions",
    "Plasma Production & Heating",
    "Plasma Thermodynamics",
    "Plasma Transport",
    "Plasma Waves",
    "Plastics",
    "Polymer Behavior",
    "Polymer Entanglement",
    "Polymer Folding",
    "Population Dynamics",
    "Protein Structure Prediction",
    "Proteomics",
    "Psychopharmacology",
    "Psychophysiology",
    "Public Health",
    "Quantum Chemistry",
    "Quantum Computing",
    "Quantum Engineering",
    "Quantum Information Processing",
    "Quantum Theory",
    "Radiobiology",
    "Regenerative Medicine",
    "Rheology",
    "Shear Flow",
    "Social Systems",
    "Sociobiology",
    "Soil Science",
    "Statistics & Probability",
    "Structural Biology",
    "Structural Engineering",
    "Superconductivity",
    "Superfluidity",
    "Surface Science",
    "Sustainability",
    "Synthetic Biology",
    "Systems Biology",
    "Taxonomy",
    "Textiles",
    "Theoretical Biology",
    "Thermodynamics",
    "Toxicology",
    "Translational Science",
    "Transportation Research",
    "Veterinary Medicine",
    "Virology",
    "Zoology",
]
